window.esdocSearchIndex = [
  [
    "aurelia-http-client/src/headers.js~headers",
    "class/src/headers.js~Headers.html",
    "<span>Headers</span> <span class=\"search-result-import-path\">aurelia-http-client/src/headers.js</span>",
    "class"
  ],
  [
    "aurelia-http-client/src/http-client.js~httpclient",
    "class/src/http-client.js~HttpClient.html",
    "<span>HttpClient</span> <span class=\"search-result-import-path\">aurelia-http-client/src/http-client.js</span>",
    "class"
  ],
  [
    "aurelia-http-client/src/http-request-message.js~httprequestmessage",
    "class/src/http-request-message.js~HttpRequestMessage.html",
    "<span>HttpRequestMessage</span> <span class=\"search-result-import-path\">aurelia-http-client/src/http-request-message.js</span>",
    "class"
  ],
  [
    "aurelia-http-client/src/http-response-message.js~httpresponsemessage",
    "class/src/http-response-message.js~HttpResponseMessage.html",
    "<span>HttpResponseMessage</span> <span class=\"search-result-import-path\">aurelia-http-client/src/http-response-message.js</span>",
    "class"
  ],
  [
    "aurelia-http-client/src/jsonp-request-message.js~jsonprequestmessage",
    "class/src/jsonp-request-message.js~JSONPRequestMessage.html",
    "<span>JSONPRequestMessage</span> <span class=\"search-result-import-path\">aurelia-http-client/src/jsonp-request-message.js</span>",
    "class"
  ],
  [
    "aurelia-http-client/src/request-builder.js~requestbuilder",
    "class/src/request-builder.js~RequestBuilder.html",
    "<span>RequestBuilder</span> <span class=\"search-result-import-path\">aurelia-http-client/src/request-builder.js</span>",
    "class"
  ],
  [
    "aurelia-http-client/src/request-message-processor.js~requestmessageprocessor",
    "class/src/request-message-processor.js~RequestMessageProcessor.html",
    "<span>RequestMessageProcessor</span> <span class=\"search-result-import-path\">aurelia-http-client/src/request-message-processor.js</span>",
    "class"
  ],
  [
    "aurelia-http-client/src/transformers.js~callbackparameternametransformer",
    "function/index.html#static-function-callbackParameterNameTransformer",
    "<span>callbackParameterNameTransformer</span> <span class=\"search-result-import-path\">aurelia-http-client/src/transformers.js</span>",
    "function"
  ],
  [
    "aurelia-http-client/src/transformers.js~contenttransformer",
    "function/index.html#static-function-contentTransformer",
    "<span>contentTransformer</span> <span class=\"search-result-import-path\">aurelia-http-client/src/transformers.js</span>",
    "function"
  ],
  [
    "aurelia-http-client/src/http-request-message.js~createhttprequestmessageprocessor",
    "function/index.html#static-function-createHttpRequestMessageProcessor",
    "<span>createHttpRequestMessageProcessor</span> <span class=\"search-result-import-path\">aurelia-http-client/src/http-request-message.js</span>",
    "function"
  ],
  [
    "aurelia-http-client/src/jsonp-request-message.js~createjsonprequestmessageprocessor",
    "function/index.html#static-function-createJSONPRequestMessageProcessor",
    "<span>createJSONPRequestMessageProcessor</span> <span class=\"search-result-import-path\">aurelia-http-client/src/jsonp-request-message.js</span>",
    "function"
  ],
  [
    "aurelia-http-client/src/transformers.js~credentialstransformer",
    "function/index.html#static-function-credentialsTransformer",
    "<span>credentialsTransformer</span> <span class=\"search-result-import-path\">aurelia-http-client/src/transformers.js</span>",
    "function"
  ],
  [
    "aurelia-http-client/src/transformers.js~headertransformer",
    "function/index.html#static-function-headerTransformer",
    "<span>headerTransformer</span> <span class=\"search-result-import-path\">aurelia-http-client/src/transformers.js</span>",
    "function"
  ],
  [
    "aurelia-http-client/src/http-response-message.js~mimetypes",
    "variable/index.html#static-variable-mimeTypes",
    "<span>mimeTypes</span> <span class=\"search-result-import-path\">aurelia-http-client/src/http-response-message.js</span>",
    "variable"
  ],
  [
    "aurelia-http-client/src/transformers.js~progresstransformer",
    "function/index.html#static-function-progressTransformer",
    "<span>progressTransformer</span> <span class=\"search-result-import-path\">aurelia-http-client/src/transformers.js</span>",
    "function"
  ],
  [
    "aurelia-http-client/src/transformers.js~responsetypetransformer",
    "function/index.html#static-function-responseTypeTransformer",
    "<span>responseTypeTransformer</span> <span class=\"search-result-import-path\">aurelia-http-client/src/transformers.js</span>",
    "function"
  ],
  [
    "aurelia-http-client/src/transformers.js~timeouttransformer",
    "function/index.html#static-function-timeoutTransformer",
    "<span>timeoutTransformer</span> <span class=\"search-result-import-path\">aurelia-http-client/src/transformers.js</span>",
    "function"
  ],
  [
    "defaultexternal/builtinexternal.js~array",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Array",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~arraybuffer",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~boolean",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Boolean",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~dataview",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~DataView",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~date",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Date",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~error",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Error",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~evalerror",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~EvalError",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~float32array",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Float32Array",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~float64array",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Float64Array",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~function",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Function",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~generator",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Generator",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~generatorfunction",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~infinity",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Infinity",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~int16array",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Int16Array",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~int32array",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Int32Array",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~int8array",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Int8Array",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~internalerror",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~InternalError",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~json",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~JSON",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~map",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Map",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~nan",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~NaN",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~number",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Number",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~object",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Object",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~promise",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Promise",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~proxy",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Proxy",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~rangeerror",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~RangeError",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~referenceerror",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~ReferenceError",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~reflect",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Reflect",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~regexp",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~RegExp",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~set",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Set",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~string",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~String",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~symbol",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Symbol",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~syntaxerror",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~SyntaxError",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~typeerror",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~TypeError",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~urierror",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~URIError",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~uint16array",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Uint16Array",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~uint32array",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Uint32Array",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~uint8array",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Uint8Array",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~uint8clampedarray",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~weakmap",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~WeakMap",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~weakset",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~WeakSet",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~boolean",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~boolean",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~function",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~function",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~null",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~null",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~number",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~number",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~object",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~object",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~string",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~string",
    "external"
  ],
  [
    "defaultexternal/builtinexternal.js~undefined",
    "external/index.html",
    "DefaultExternal/BuiltinExternal.js~undefined",
    "external"
  ],
  [
    "defaultexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "DefaultExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "defaultexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "DefaultExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "defaultexternal/webapiexternal.js~element",
    "external/index.html",
    "DefaultExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "defaultexternal/webapiexternal.js~event",
    "external/index.html",
    "DefaultExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "defaultexternal/webapiexternal.js~node",
    "external/index.html",
    "DefaultExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "defaultexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "DefaultExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "defaultexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "DefaultExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber4",
    "HttpResponseMessage",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber6",
    "HttpResponseMessage constructor",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber30",
    "HttpResponseMessage constructor have the xhr.status, xhr.response, xhr.statusText, responseType, reviver and headers as fields",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber7",
    "HttpResponseMessage constructor should have a isSuccess defined by the xhr.status",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber45",
    "HttpResponseMessage constructor will call the Headers.parse() if xhr.getAllResponseHeaders() is defined",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber55",
    "HttpResponseMessage constructor will set responseType to an aliased version of the mimetype detected in the Content-Type header, will also store the original mimetype as mimeType",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber78",
    "HttpResponseMessage constructor will set responseType to the responseType specified in the request if no Content-Type header was found, mimeType will be null",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber63",
    "HttpResponseMessage constructor will split the Content-Type using the ; delimeter and use the first part as the mimeType",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber87",
    "HttpResponseMessage constructor will use json if no responseType for the request was null",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber71",
    "HttpResponseMessage constructor will use the mimeType as the responseType if there is no alias for it in the mimeTypes map",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber94",
    "HttpResponseMessage content",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber112",
    "HttpResponseMessage content will JSON.parse if the response type is 'json'",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber121",
    "HttpResponseMessage content will call the reviver if the response type is not 'json' and the reviver is defined",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber137",
    "HttpResponseMessage content will catch expections on content if the response was not successful",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber95",
    "HttpResponseMessage content will return _content if defined",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber107",
    "HttpResponseMessage content will return null if response is null",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber130",
    "HttpResponseMessage content will return the response if the reviver is not set and the response type is not json",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber102",
    "HttpResponseMessage content will return undefined if response is undefined",
    "test"
  ],
  [
    "",
    "test-file/test/http-response-message.spec.js.html#lineNumber145",
    "HttpResponseMessage content will throw on content if the response was successful",
    "test"
  ],
  [
    "",
    "test-file/test/jsonp-request-message.spec.js.html#lineNumber6",
    "JSONPRequestMessage",
    "test"
  ],
  [
    "",
    "test-file/test/jsonp-request-message.spec.js.html#lineNumber18",
    "JSONPRequestMessage createJSONPRequestMessageProcessor",
    "test"
  ],
  [
    "",
    "test-file/test/jsonp-request-message.spec.js.html#lineNumber19",
    "JSONPRequestMessage createJSONPRequestMessageProcessor should create a RequestMessageProcessor with an JSONPXHR and the correct transformers",
    "test"
  ],
  [
    "",
    "test-file/test/jsonp-request-message.spec.js.html#lineNumber7",
    "JSONPRequestMessage should have a constructor that correctly sets the methods and response type",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber4",
    "Request message processor",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber14",
    "Request message processor abort() tell the request to abort",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber21",
    "Request message processor abort() won't throw if the request hasn't started yet",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber5",
    "Request message processor constructor() correctly setup the xhrType and the transformers",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber26",
    "Request message processor process()",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber56",
    "Request message processor process() should call xhr.open with the method, full url and ajax set to true",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber61",
    "Request message processor process() should call xhr.send with the message content",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber51",
    "Request message processor process() should create a new instance of the XHRType",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber74",
    "Request message processor process() should run through all the transformers",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber66",
    "Request message processor process() will combine the message baseUrl and message url and set it to the fullUrl",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber164",
    "Request message processor process() will reject if the onabort was called",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber148",
    "Request message processor process() will reject if the onerror was called",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber109",
    "Request message processor process() will reject if the onload response has failed",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber132",
    "Request message processor process() will reject if the ontimeout was called",
    "test"
  ],
  [
    "",
    "test-file/test/request-message-processor.spec.js.html#lineNumber86",
    "Request message processor process() will resolve if the onload response is successful",
    "test"
  ],
  [
    "",
    "test-file/test/headers.spec.js.html#lineNumber3",
    "headers",
    "test"
  ],
  [
    "",
    "test-file/test/headers.spec.js.html#lineNumber5",
    "headers can add header value",
    "test"
  ],
  [
    "",
    "test-file/test/headers.spec.js.html#lineNumber12",
    "headers can get header value",
    "test"
  ],
  [
    "",
    "test-file/test/headers.spec.js.html#lineNumber31",
    "headers configureXHR should add the headers",
    "test"
  ],
  [
    "",
    "test-file/test/headers.spec.js.html#lineNumber48",
    "headers parse()",
    "test"
  ],
  [
    "",
    "test-file/test/headers.spec.js.html#lineNumber55",
    "headers parse() should parse header strings",
    "test"
  ],
  [
    "",
    "test-file/test/headers.spec.js.html#lineNumber62",
    "headers parse() should parse headers with values of ': '",
    "test"
  ],
  [
    "",
    "test-file/test/headers.spec.js.html#lineNumber49",
    "headers parse() should return a new instance on undefined, null or empty string",
    "test"
  ],
  [
    "",
    "test-file/test/headers.spec.js.html#lineNumber19",
    "headers will clear headers on clear",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber5",
    "http client",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber416",
    "http client delete",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber418",
    "http client delete request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber420",
    "http client delete request should make expected request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber433",
    "http client delete request should provide expected request headers",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber449",
    "http client delete response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber465",
    "http client delete response should not succeed on 500 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber451",
    "http client delete response should succeed on 200 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber17",
    "http client get",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber19",
    "http client get request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber21",
    "http client get request should make expected request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber34",
    "http client get request should provide expected request headers",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber50",
    "http client get response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber80",
    "http client get response should not succeed on 500 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber66",
    "http client get response should retrieve correct content",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber52",
    "http client get response should succeed on 200 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber205",
    "http client patch",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber207",
    "http client patch request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber209",
    "http client patch request should make expected request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber226",
    "http client patch request should only include content properties specified in the replacer array",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber246",
    "http client patch request should provide expected request headers",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber262",
    "http client patch response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber292",
    "http client patch response should not succeed on 500 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber278",
    "http client patch response should retrieve correct content",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber264",
    "http client patch response should succeed on 200 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber311",
    "http client post",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber313",
    "http client post request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber315",
    "http client post request should make expected request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber332",
    "http client post request should only include content properties specified in the replacer array",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber352",
    "http client post request should provide expected request headers",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber368",
    "http client post response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber398",
    "http client post response should not succeed on 500 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber384",
    "http client post response should retrieve correct content",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber370",
    "http client post response should succeed on 201 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber99",
    "http client put",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber101",
    "http client put request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber103",
    "http client put request should make expected request",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber120",
    "http client put request should only include content properties specified in the replacer array",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber140",
    "http client put request should provide expected request headers",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber156",
    "http client put response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber186",
    "http client put response should not succeed on 500 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber172",
    "http client put response should retrieve correct content",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber158",
    "http client put response should succeed on 200 response",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber484",
    "http client send",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber565",
    "http client send can parse header values containing :",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber545",
    "http client send can parse multiple request headers",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber526",
    "http client send can parse request headers",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber486",
    "http client send should reject on onerror",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber499",
    "http client send should reject on ontimeout",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber513",
    "http client send should reject when aborted",
    "test"
  ],
  [
    "",
    "test-file/test/http-client.spec.js.html#lineNumber580",
    "http client send should set callback on upload progress",
    "test"
  ],
  [
    "",
    "test-file/test/http-request-message.spec.js.html#lineNumber13",
    "http-request-message",
    "test"
  ],
  [
    "",
    "test-file/test/http-request-message.spec.js.html#lineNumber32",
    "http-request-message createHttpRequestMessageProcessor",
    "test"
  ],
  [
    "",
    "test-file/test/http-request-message.spec.js.html#lineNumber33",
    "http-request-message createHttpRequestMessageProcessor should create a RequestMessageProcessor with an XMLHttpRequest and the correct transformers",
    "test"
  ],
  [
    "",
    "test-file/test/http-request-message.spec.js.html#lineNumber26",
    "http-request-message have a constructor should default the headers if not provided",
    "test"
  ],
  [
    "",
    "test-file/test/http-request-message.spec.js.html#lineNumber15",
    "http-request-message should have a constructor that takes in the method, url, content and headers",
    "test"
  ],
  [
    "src/headers.js",
    "file/src/headers.js.html",
    "src/headers.js",
    "file"
  ],
  [
    "src/headers.js~headers#add",
    "class/src/headers.js~Headers.html#instance-method-add",
    "src/headers.js~Headers#add",
    "method"
  ],
  [
    "src/headers.js~headers#clear",
    "class/src/headers.js~Headers.html#instance-method-clear",
    "src/headers.js~Headers#clear",
    "method"
  ],
  [
    "src/headers.js~headers#configurexhr",
    "class/src/headers.js~Headers.html#instance-method-configureXHR",
    "src/headers.js~Headers#configureXHR",
    "method"
  ],
  [
    "src/headers.js~headers#constructor",
    "class/src/headers.js~Headers.html#instance-constructor-constructor",
    "src/headers.js~Headers#constructor",
    "method"
  ],
  [
    "src/headers.js~headers#get",
    "class/src/headers.js~Headers.html#instance-method-get",
    "src/headers.js~Headers#get",
    "method"
  ],
  [
    "src/headers.js~headers#headers",
    "class/src/headers.js~Headers.html#instance-member-headers",
    "src/headers.js~Headers#headers",
    "member"
  ],
  [
    "src/headers.js~headers#headers",
    "class/src/headers.js~Headers.html#instance-member-headers",
    "src/headers.js~Headers#headers",
    "member"
  ],
  [
    "src/headers.js~headers.parse",
    "class/src/headers.js~Headers.html#static-method-parse",
    "src/headers.js~Headers.parse",
    "method"
  ],
  [
    "src/http-client.js",
    "file/src/http-client.js.html",
    "src/http-client.js",
    "file"
  ],
  [
    "src/http-client.js~httpclient#configure",
    "class/src/http-client.js~HttpClient.html#instance-method-configure",
    "src/http-client.js~HttpClient#configure",
    "method"
  ],
  [
    "src/http-client.js~httpclient#constructor",
    "class/src/http-client.js~HttpClient.html#instance-constructor-constructor",
    "src/http-client.js~HttpClient#constructor",
    "method"
  ],
  [
    "src/http-client.js~httpclient#createrequest",
    "class/src/http-client.js~HttpClient.html#instance-method-createRequest",
    "src/http-client.js~HttpClient#createRequest",
    "method"
  ],
  [
    "src/http-client.js~httpclient#delete",
    "class/src/http-client.js~HttpClient.html#instance-method-delete",
    "src/http-client.js~HttpClient#delete",
    "method"
  ],
  [
    "src/http-client.js~httpclient#get",
    "class/src/http-client.js~HttpClient.html#instance-method-get",
    "src/http-client.js~HttpClient#get",
    "method"
  ],
  [
    "src/http-client.js~httpclient#head",
    "class/src/http-client.js~HttpClient.html#instance-method-head",
    "src/http-client.js~HttpClient#head",
    "method"
  ],
  [
    "src/http-client.js~httpclient#isrequesting",
    "class/src/http-client.js~HttpClient.html#instance-member-isRequesting",
    "src/http-client.js~HttpClient#isRequesting",
    "member"
  ],
  [
    "src/http-client.js~httpclient#jsonp",
    "class/src/http-client.js~HttpClient.html#instance-method-jsonp",
    "src/http-client.js~HttpClient#jsonp",
    "method"
  ],
  [
    "src/http-client.js~httpclient#options",
    "class/src/http-client.js~HttpClient.html#instance-method-options",
    "src/http-client.js~HttpClient#options",
    "method"
  ],
  [
    "src/http-client.js~httpclient#patch",
    "class/src/http-client.js~HttpClient.html#instance-method-patch",
    "src/http-client.js~HttpClient#patch",
    "method"
  ],
  [
    "src/http-client.js~httpclient#pendingrequests",
    "class/src/http-client.js~HttpClient.html#instance-member-pendingRequests",
    "src/http-client.js~HttpClient#pendingRequests",
    "member"
  ],
  [
    "src/http-client.js~httpclient#post",
    "class/src/http-client.js~HttpClient.html#instance-method-post",
    "src/http-client.js~HttpClient#post",
    "method"
  ],
  [
    "src/http-client.js~httpclient#put",
    "class/src/http-client.js~HttpClient.html#instance-method-put",
    "src/http-client.js~HttpClient#put",
    "method"
  ],
  [
    "src/http-client.js~httpclient#requestprocessorfactories",
    "class/src/http-client.js~HttpClient.html#instance-member-requestProcessorFactories",
    "src/http-client.js~HttpClient#requestProcessorFactories",
    "member"
  ],
  [
    "src/http-client.js~httpclient#requesttransformers",
    "class/src/http-client.js~HttpClient.html#instance-member-requestTransformers",
    "src/http-client.js~HttpClient#requestTransformers",
    "member"
  ],
  [
    "src/http-client.js~httpclient#requesttransformers",
    "class/src/http-client.js~HttpClient.html#instance-member-requestTransformers",
    "src/http-client.js~HttpClient#requestTransformers",
    "member"
  ],
  [
    "src/http-client.js~httpclient#send",
    "class/src/http-client.js~HttpClient.html#instance-method-send",
    "src/http-client.js~HttpClient#send",
    "method"
  ],
  [
    "src/http-request-message.js",
    "file/src/http-request-message.js.html",
    "src/http-request-message.js",
    "file"
  ],
  [
    "src/http-request-message.js~httprequestmessage#constructor",
    "class/src/http-request-message.js~HttpRequestMessage.html#instance-constructor-constructor",
    "src/http-request-message.js~HttpRequestMessage#constructor",
    "method"
  ],
  [
    "src/http-request-message.js~httprequestmessage#content",
    "class/src/http-request-message.js~HttpRequestMessage.html#instance-member-content",
    "src/http-request-message.js~HttpRequestMessage#content",
    "member"
  ],
  [
    "src/http-request-message.js~httprequestmessage#headers",
    "class/src/http-request-message.js~HttpRequestMessage.html#instance-member-headers",
    "src/http-request-message.js~HttpRequestMessage#headers",
    "member"
  ],
  [
    "src/http-request-message.js~httprequestmessage#method",
    "class/src/http-request-message.js~HttpRequestMessage.html#instance-member-method",
    "src/http-request-message.js~HttpRequestMessage#method",
    "member"
  ],
  [
    "src/http-request-message.js~httprequestmessage#responsetype",
    "class/src/http-request-message.js~HttpRequestMessage.html#instance-member-responseType",
    "src/http-request-message.js~HttpRequestMessage#responseType",
    "member"
  ],
  [
    "src/http-request-message.js~httprequestmessage#url",
    "class/src/http-request-message.js~HttpRequestMessage.html#instance-member-url",
    "src/http-request-message.js~HttpRequestMessage#url",
    "member"
  ],
  [
    "src/http-response-message.js",
    "file/src/http-response-message.js.html",
    "src/http-response-message.js",
    "file"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#constructor",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-constructor-constructor",
    "src/http-response-message.js~HttpResponseMessage#constructor",
    "method"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#content",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-get-content",
    "src/http-response-message.js~HttpResponseMessage#content",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#headers",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-headers",
    "src/http-response-message.js~HttpResponseMessage#headers",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#headers",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-headers",
    "src/http-response-message.js~HttpResponseMessage#headers",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#headers",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-headers",
    "src/http-response-message.js~HttpResponseMessage#headers",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#issuccess",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-isSuccess",
    "src/http-response-message.js~HttpResponseMessage#isSuccess",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#mimetype",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-mimeType",
    "src/http-response-message.js~HttpResponseMessage#mimeType",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#mimetype",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-mimeType",
    "src/http-response-message.js~HttpResponseMessage#mimeType",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#requestmessage",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-requestMessage",
    "src/http-response-message.js~HttpResponseMessage#requestMessage",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#response",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-response",
    "src/http-response-message.js~HttpResponseMessage#response",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#responsetype",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-responseType",
    "src/http-response-message.js~HttpResponseMessage#responseType",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#reviver",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-reviver",
    "src/http-response-message.js~HttpResponseMessage#reviver",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#statuscode",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-statusCode",
    "src/http-response-message.js~HttpResponseMessage#statusCode",
    "member"
  ],
  [
    "src/http-response-message.js~httpresponsemessage#statustext",
    "class/src/http-response-message.js~HttpResponseMessage.html#instance-member-statusText",
    "src/http-response-message.js~HttpResponseMessage#statusText",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/jsonp-request-message.js",
    "file/src/jsonp-request-message.js.html",
    "src/jsonp-request-message.js",
    "file"
  ],
  [
    "src/jsonp-request-message.js~jsonprequestmessage#callbackparametername",
    "class/src/jsonp-request-message.js~JSONPRequestMessage.html#instance-member-callbackParameterName",
    "src/jsonp-request-message.js~JSONPRequestMessage#callbackParameterName",
    "member"
  ],
  [
    "src/jsonp-request-message.js~jsonprequestmessage#constructor",
    "class/src/jsonp-request-message.js~JSONPRequestMessage.html#instance-constructor-constructor",
    "src/jsonp-request-message.js~JSONPRequestMessage#constructor",
    "method"
  ],
  [
    "src/jsonp-request-message.js~jsonprequestmessage#content",
    "class/src/jsonp-request-message.js~JSONPRequestMessage.html#instance-member-content",
    "src/jsonp-request-message.js~JSONPRequestMessage#content",
    "member"
  ],
  [
    "src/jsonp-request-message.js~jsonprequestmessage#headers",
    "class/src/jsonp-request-message.js~JSONPRequestMessage.html#instance-member-headers",
    "src/jsonp-request-message.js~JSONPRequestMessage#headers",
    "member"
  ],
  [
    "src/jsonp-request-message.js~jsonprequestmessage#method",
    "class/src/jsonp-request-message.js~JSONPRequestMessage.html#instance-member-method",
    "src/jsonp-request-message.js~JSONPRequestMessage#method",
    "member"
  ],
  [
    "src/jsonp-request-message.js~jsonprequestmessage#responsetype",
    "class/src/jsonp-request-message.js~JSONPRequestMessage.html#instance-member-responseType",
    "src/jsonp-request-message.js~JSONPRequestMessage#responseType",
    "member"
  ],
  [
    "src/jsonp-request-message.js~jsonprequestmessage#url",
    "class/src/jsonp-request-message.js~JSONPRequestMessage.html#instance-member-url",
    "src/jsonp-request-message.js~JSONPRequestMessage#url",
    "member"
  ],
  [
    "src/request-builder.js",
    "file/src/request-builder.js.html",
    "src/request-builder.js",
    "file"
  ],
  [
    "src/request-builder.js~requestbuilder#client",
    "class/src/request-builder.js~RequestBuilder.html#instance-member-client",
    "src/request-builder.js~RequestBuilder#client",
    "member"
  ],
  [
    "src/request-builder.js~requestbuilder#constructor",
    "class/src/request-builder.js~RequestBuilder.html#instance-constructor-constructor",
    "src/request-builder.js~RequestBuilder#constructor",
    "method"
  ],
  [
    "src/request-builder.js~requestbuilder#send",
    "class/src/request-builder.js~RequestBuilder.html#instance-method-send",
    "src/request-builder.js~RequestBuilder#send",
    "method"
  ],
  [
    "src/request-builder.js~requestbuilder#transformers",
    "class/src/request-builder.js~RequestBuilder.html#instance-member-transformers",
    "src/request-builder.js~RequestBuilder#transformers",
    "member"
  ],
  [
    "src/request-builder.js~requestbuilder#usejsonp",
    "class/src/request-builder.js~RequestBuilder.html#instance-member-useJsonp",
    "src/request-builder.js~RequestBuilder#useJsonp",
    "member"
  ],
  [
    "src/request-builder.js~requestbuilder.addhelper",
    "class/src/request-builder.js~RequestBuilder.html#static-method-addHelper",
    "src/request-builder.js~RequestBuilder.addHelper",
    "method"
  ],
  [
    "src/request-message-processor.js",
    "file/src/request-message-processor.js.html",
    "src/request-message-processor.js",
    "file"
  ],
  [
    "src/request-message-processor.js~requestmessageprocessor#xhrtype",
    "class/src/request-message-processor.js~RequestMessageProcessor.html#instance-member-XHRType",
    "src/request-message-processor.js~RequestMessageProcessor#XHRType",
    "member"
  ],
  [
    "src/request-message-processor.js~requestmessageprocessor#abort",
    "class/src/request-message-processor.js~RequestMessageProcessor.html#instance-method-abort",
    "src/request-message-processor.js~RequestMessageProcessor#abort",
    "method"
  ],
  [
    "src/request-message-processor.js~requestmessageprocessor#constructor",
    "class/src/request-message-processor.js~RequestMessageProcessor.html#instance-constructor-constructor",
    "src/request-message-processor.js~RequestMessageProcessor#constructor",
    "method"
  ],
  [
    "src/request-message-processor.js~requestmessageprocessor#process",
    "class/src/request-message-processor.js~RequestMessageProcessor.html#instance-method-process",
    "src/request-message-processor.js~RequestMessageProcessor#process",
    "method"
  ],
  [
    "src/request-message-processor.js~requestmessageprocessor#transformers",
    "class/src/request-message-processor.js~RequestMessageProcessor.html#instance-member-transformers",
    "src/request-message-processor.js~RequestMessageProcessor#transformers",
    "member"
  ],
  [
    "src/transformers.js",
    "file/src/transformers.js.html",
    "src/transformers.js",
    "file"
  ],
  [
    "test/headers.spec.js",
    "test-file/test/headers.spec.js.html",
    "test/headers.spec.js",
    "testFile"
  ],
  [
    "test/http-client.spec.js",
    "test-file/test/http-client.spec.js.html",
    "test/http-client.spec.js",
    "testFile"
  ],
  [
    "test/http-request-message.spec.js",
    "test-file/test/http-request-message.spec.js.html",
    "test/http-request-message.spec.js",
    "testFile"
  ],
  [
    "test/http-response-message.spec.js",
    "test-file/test/http-response-message.spec.js.html",
    "test/http-response-message.spec.js",
    "testFile"
  ],
  [
    "test/jsonp-request-message.spec.js",
    "test-file/test/jsonp-request-message.spec.js.html",
    "test/jsonp-request-message.spec.js",
    "testFile"
  ],
  [
    "test/request-message-processor.spec.js",
    "test-file/test/request-message-processor.spec.js.html",
    "test/request-message-processor.spec.js",
    "testFile"
  ],
  [
    "test/transformers.spec.js",
    "test-file/test/transformers.spec.js.html",
    "test/transformers.spec.js",
    "testFile"
  ],
  [
    "",
    "test-file/test/transformers.spec.js.html#lineNumber3",
    "transformers",
    "test"
  ],
  [
    "",
    "test-file/test/transformers.spec.js.html#lineNumber15",
    "transformers callbackParameterNameTransformer should set the xhr.callbackParameterName if defined in the message",
    "test"
  ],
  [
    "",
    "test-file/test/transformers.spec.js.html#lineNumber25",
    "transformers credentialsTransformer should set the xhr.withCredentials if defined in the message",
    "test"
  ],
  [
    "",
    "test-file/test/transformers.spec.js.html#lineNumber36",
    "transformers responseTypeTransformer should change the responseType to text when it's json",
    "test"
  ],
  [
    "",
    "test-file/test/transformers.spec.js.html#lineNumber5",
    "transformers timeout should set the xhr timeout to the message timeout if defined in the message",
    "test"
  ]
]