window.jsdocCloudySearchIndex = [
  [
    "esdoc-test-fixture~myclass1",
    "%40class-src%7CMyClass.js~MyClass1.html",
    "<span>MyClass1</span> <span class=\"search-result-import-path\">esdoc-test-fixture</span>"
  ],
  [
    "esdoc-test-fixture~myclass2",
    "%40class-src%7CMyClass.js~MyClass2.html",
    "<span>MyClass2</span> <span class=\"search-result-import-path\">esdoc-test-fixture</span>"
  ],
  [
    "esdoc-test-fixture~myclass3",
    "%40class-src%7CMyClass.js~MyClass3.html",
    "<span>MyClass3</span> <span class=\"search-result-import-path\">esdoc-test-fixture</span>"
  ],
  [
    "esdoc-test-fixture~myclass4",
    "%40class-src%7CMyClass.js~MyClass4.html",
    "<span>MyClass4</span> <span class=\"search-result-import-path\">esdoc-test-fixture</span>"
  ],
  [
    "esdoc-test-fixture~myclass5",
    "%40class-src%7CMyClass.js~MyClass5.html",
    "<span>MyClass5</span> <span class=\"search-result-import-path\">esdoc-test-fixture</span>"
  ],
  [
    "esdoc-test-fixture~myclass6",
    "%40class-src%7CMyClass.js~MyClass6.html",
    "<span>MyClass6</span> <span class=\"search-result-import-path\">esdoc-test-fixture</span>"
  ],
  [
    "esdoc-test-fixture/src/myerror.js~myerror1",
    "%40class-src%7CMyError.js~MyError1.html",
    "<span>MyError1</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/MyError.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myevent.js~myevent1",
    "%40class-src%7CMyEvent.js~MyEvent1.html",
    "<span>MyEvent1</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/MyEvent.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myinterface.js~myinterface1",
    "%40class-src%7CMyInterface.js~MyInterface1.html",
    "<span>MyInterface1</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/MyInterface.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myinterface.js~myinterface2",
    "%40class-src%7CMyInterface.js~MyInterface2.html",
    "<span>MyInterface2</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/MyInterface.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myinterface.js~myinterface3",
    "%40class-src%7CMyInterface.js~MyInterface3.html",
    "<span>MyInterface3</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/MyInterface.js</span>"
  ],
  [
    "esdoc-test-fixture/src/otherclass/supermyclass.js~supermyclass1",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html",
    "<span>SuperMyClass1</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/OtherClass/SuperMyClass.js</span>"
  ],
  [
    "esdoc-test-fixture/src/otherclass/supermyclass.js~supermyclass2",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass2.html",
    "<span>SuperMyClass2</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/OtherClass/SuperMyClass.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myfunction.js~myfunction1",
    "%40function.html#static-function-myFunction1",
    "<span>myFunction1</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/myFunction.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myfunction.js~myfunction2",
    "%40function.html#static-function-myFunction2",
    "<span>myFunction2</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/myFunction.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myfunction.js~myfunction3",
    "%40function.html#static-function-myFunction3",
    "<span>myFunction3</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/myFunction.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myfunction.js~myfunction4",
    "%40function.html#static-function-myFunction4",
    "<span>myFunction4</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/myFunction.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myfunction.js~myfunction5",
    "%40function.html#static-function-myFunction5",
    "<span>myFunction5</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/myFunction.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myvariable.js~myvariable1",
    "%40variable.html#static-variable-myVariable1",
    "<span>myVariable1</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/myVariable.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myvariable.js~myvariable2",
    "%40variable.html#static-variable-myVariable2",
    "<span>myVariable2</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/myVariable.js</span>"
  ],
  [
    "esdoc-test-fixture/src/myvariable.js~myvariable3",
    "%40variable.html#static-variable-myVariable3",
    "<span>myVariable3</span> <span class=\"search-result-import-path\">esdoc-test-fixture/src/myVariable.js</span>"
  ],
  [
    "src/myclass.js",
    "%40file-src%7CMyClass.js.html",
    "src/MyClass.js"
  ],
  [
    "src/myclass.js~myclass1#constructor",
    "%40class-src%7CMyClass.js~MyClass1.html#instance-constructor-constructor",
    "src/MyClass.js~MyClass1#constructor"
  ],
  [
    "src/myclass.js~myclass1#method1",
    "%40class-src%7CMyClass.js~MyClass1.html#instance-method-method1",
    "src/MyClass.js~MyClass1#method1"
  ],
  [
    "src/myclass.js~myclass1#method2",
    "%40class-src%7CMyClass.js~MyClass1.html#instance-method-method2",
    "src/MyClass.js~MyClass1#method2"
  ],
  [
    "src/myclass.js~myclass1#method3",
    "%40class-src%7CMyClass.js~MyClass1.html#instance-method-method3",
    "src/MyClass.js~MyClass1#method3"
  ],
  [
    "src/myclass.js~myclass1#p1",
    "%40class-src%7CMyClass.js~MyClass1.html#instance-member-p1",
    "src/MyClass.js~MyClass1#p1"
  ],
  [
    "src/myclass.js~myclass1#p2",
    "%40class-src%7CMyClass.js~MyClass1.html#instance-member-p2",
    "src/MyClass.js~MyClass1#p2"
  ],
  [
    "src/myclass.js~myclass1#p3",
    "%40class-src%7CMyClass.js~MyClass1.html#instance-member-p3",
    "src/MyClass.js~MyClass1#p3"
  ],
  [
    "src/myclass.js~myclass1#value",
    "%40class-src%7CMyClass.js~MyClass1.html#instance-get-value",
    "src/MyClass.js~MyClass1#value"
  ],
  [
    "src/myclass.js~myclass1#value",
    "%40class-src%7CMyClass.js~MyClass1.html#instance-set-value",
    "src/MyClass.js~MyClass1#value"
  ],
  [
    "src/myclass.js~myclass1.p1",
    "%40class-src%7CMyClass.js~MyClass1.html#static-member-p1",
    "src/MyClass.js~MyClass1.p1"
  ],
  [
    "src/myclass.js~myclass1.p2",
    "%40class-src%7CMyClass.js~MyClass1.html#static-member-p2",
    "src/MyClass.js~MyClass1.p2"
  ],
  [
    "src/myclass.js~myclass1.p3",
    "%40class-src%7CMyClass.js~MyClass1.html#static-member-p3",
    "src/MyClass.js~MyClass1.p3"
  ],
  [
    "src/myclass.js~myclass1.staticmethod1",
    "%40class-src%7CMyClass.js~MyClass1.html#static-method-staticMethod1",
    "src/MyClass.js~MyClass1.staticMethod1"
  ],
  [
    "src/myclass.js~myclass1.staticmethod2",
    "%40class-src%7CMyClass.js~MyClass1.html#static-method-staticMethod2",
    "src/MyClass.js~MyClass1.staticMethod2"
  ],
  [
    "src/myclass.js~myclass1.staticmethod3",
    "%40class-src%7CMyClass.js~MyClass1.html#static-method-staticMethod3",
    "src/MyClass.js~MyClass1.staticMethod3"
  ],
  [
    "src/myclass.js~myclass1.staticvalue",
    "%40class-src%7CMyClass.js~MyClass1.html#static-get-staticValue",
    "src/MyClass.js~MyClass1.staticValue"
  ],
  [
    "src/myclass.js~myclass1.staticvalue",
    "%40class-src%7CMyClass.js~MyClass1.html#static-set-staticValue",
    "src/MyClass.js~MyClass1.staticValue"
  ],
  [
    "src/myerror.js",
    "%40file-src%7CMyError.js.html",
    "src/MyError.js"
  ],
  [
    "src/myerror.js~myerror2",
    "%40external.html",
    "src/MyError.js~MyError2"
  ],
  [
    "src/myevent.js",
    "%40file-src%7CMyEvent.js.html",
    "src/MyEvent.js"
  ],
  [
    "src/myevent.js~myevent2",
    "%40external.html",
    "src/MyEvent.js~MyEvent2"
  ],
  [
    "src/myinterface.js",
    "%40file-src%7CMyInterface.js.html",
    "src/MyInterface.js"
  ],
  [
    "src/mytypedef.js",
    "%40file-src%7CMyTypedef.js.html",
    "src/MyTypedef.js"
  ],
  [
    "src/mytypedef.js~mytypedef1",
    "%40typedef.html#static-typedef-MyTypedef1",
    "src/MyTypedef.js~MyTypedef1"
  ],
  [
    "src/otherclass/supermyclass.js",
    "%40file-src%7COtherClass%7CSuperMyClass.js.html",
    "src/OtherClass/SuperMyClass.js"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass1#method1",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html#instance-method-method1",
    "src/OtherClass/SuperMyClass.js~SuperMyClass1#method1"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass1#supermethod",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html#instance-method-superMethod",
    "src/OtherClass/SuperMyClass.js~SuperMyClass1#superMethod"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass1#superp1",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html#instance-member-superP1",
    "src/OtherClass/SuperMyClass.js~SuperMyClass1#superP1"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass1#supervalue",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html#instance-set-superValue",
    "src/OtherClass/SuperMyClass.js~SuperMyClass1#superValue"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass1#supervalue",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html#instance-get-superValue",
    "src/OtherClass/SuperMyClass.js~SuperMyClass1#superValue"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass1.superp1",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html#static-member-superP1",
    "src/OtherClass/SuperMyClass.js~SuperMyClass1.superP1"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass1.superstaticmethod",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html#static-method-superStaticMethod",
    "src/OtherClass/SuperMyClass.js~SuperMyClass1.superStaticMethod"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass1.superstaticvalue",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html#static-set-superStaticValue",
    "src/OtherClass/SuperMyClass.js~SuperMyClass1.superStaticValue"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass1.superstaticvalue",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass1.html#static-get-superStaticValue",
    "src/OtherClass/SuperMyClass.js~SuperMyClass1.superStaticValue"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass2#ultramethod",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass2.html#instance-method-ultraMethod",
    "src/OtherClass/SuperMyClass.js~SuperMyClass2#ultraMethod"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass2#ultrap1",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass2.html#instance-member-ultraP1",
    "src/OtherClass/SuperMyClass.js~SuperMyClass2#ultraP1"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass2#ultravalue",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass2.html#instance-set-ultraValue",
    "src/OtherClass/SuperMyClass.js~SuperMyClass2#ultraValue"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass2#ultravalue",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass2.html#instance-get-ultraValue",
    "src/OtherClass/SuperMyClass.js~SuperMyClass2#ultraValue"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass2.ultrap1",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass2.html#static-member-ultraP1",
    "src/OtherClass/SuperMyClass.js~SuperMyClass2.ultraP1"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass2.ultrastaticmethod",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass2.html#static-method-ultraStaticMethod",
    "src/OtherClass/SuperMyClass.js~SuperMyClass2.ultraStaticMethod"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass2.ultrastaticvalue",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass2.html#static-set-ultraStaticValue",
    "src/OtherClass/SuperMyClass.js~SuperMyClass2.ultraStaticValue"
  ],
  [
    "src/otherclass/supermyclass.js~supermyclass2.ultrastaticvalue",
    "%40class-src%7COtherClass%7CSuperMyClass.js~SuperMyClass2.html#static-get-ultraStaticValue",
    "src/OtherClass/SuperMyClass.js~SuperMyClass2.ultraStaticValue"
  ],
  [
    "src/external.js",
    "%40file-src%7Cexternal.js.html",
    "src/external.js"
  ],
  [
    "src/external.js~xmlhttprequest",
    "%40external.html",
    "src/external.js~XMLHttpRequest"
  ],
  [
    "src/external.js~number",
    "%40external.html",
    "src/external.js~number"
  ],
  [
    "src/external.js~string",
    "%40external.html",
    "src/external.js~string"
  ],
  [
    "src/myfunction.js",
    "%40file-src%7CmyFunction.js.html",
    "src/myFunction.js"
  ],
  [
    "src/myvariable.js",
    "%40file-src%7CmyVariable.js.html",
    "src/myVariable.js"
  ]
]