window.jsdocCloudySearchIndex = [
  [
    "color-logger~colorlogger",
    "%40class-src%7CColorLogger.js~ColorLogger.html",
    "<span>ColorLogger</span> <span class=\"search-result-import-path\">color-logger</span>"
  ],
  [
    "src/colorlogger.js",
    "%40file-src%7CColorLogger.js.html",
    "src/ColorLogger.js"
  ],
  [
    "src/colorlogger.js~colorlogger#constructor",
    "%40class-src%7CColorLogger.js~ColorLogger.html#instance-constructor-constructor",
    "src/ColorLogger.js~ColorLogger#constructor"
  ],
  [
    "src/colorlogger.js~colorlogger#d",
    "%40class-src%7CColorLogger.js~ColorLogger.html#instance-method-d",
    "src/ColorLogger.js~ColorLogger#d"
  ],
  [
    "src/colorlogger.js~colorlogger#e",
    "%40class-src%7CColorLogger.js~ColorLogger.html#instance-method-e",
    "src/ColorLogger.js~ColorLogger#e"
  ],
  [
    "src/colorlogger.js~colorlogger#i",
    "%40class-src%7CColorLogger.js~ColorLogger.html#instance-method-i",
    "src/ColorLogger.js~ColorLogger#i"
  ],
  [
    "src/colorlogger.js~colorlogger#v",
    "%40class-src%7CColorLogger.js~ColorLogger.html#instance-method-v",
    "src/ColorLogger.js~ColorLogger#v"
  ],
  [
    "src/colorlogger.js~colorlogger#w",
    "%40class-src%7CColorLogger.js~ColorLogger.html#instance-method-w",
    "src/ColorLogger.js~ColorLogger#w"
  ],
  [
    "src/colorlogger.js~colorlogger.d",
    "%40class-src%7CColorLogger.js~ColorLogger.html#static-method-d",
    "src/ColorLogger.js~ColorLogger.d"
  ],
  [
    "src/colorlogger.js~colorlogger.debug",
    "%40class-src%7CColorLogger.js~ColorLogger.html#static-set-debug",
    "src/ColorLogger.js~ColorLogger.debug"
  ],
  [
    "src/colorlogger.js~colorlogger.e",
    "%40class-src%7CColorLogger.js~ColorLogger.html#static-method-e",
    "src/ColorLogger.js~ColorLogger.e"
  ],
  [
    "src/colorlogger.js~colorlogger.i",
    "%40class-src%7CColorLogger.js~ColorLogger.html#static-method-i",
    "src/ColorLogger.js~ColorLogger.i"
  ],
  [
    "src/colorlogger.js~colorlogger.v",
    "%40class-src%7CColorLogger.js~ColorLogger.html#static-method-v",
    "src/ColorLogger.js~ColorLogger.v"
  ],
  [
    "src/colorlogger.js~colorlogger.w",
    "%40class-src%7CColorLogger.js~ColorLogger.html#static-method-w",
    "src/ColorLogger.js~ColorLogger.w"
  ]
]